# Generated by Django 3.0.5 on 2020-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_places_uz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sura_name', models.CharField(max_length=200)),
                ('ayat_number', models.CharField(max_length=8)),
                ('ayat_translation_uz', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='get_places',
        ),
    ]
