# Generated by Django 3.0.5 on 2020-04-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20200418_1440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='get_places_uz',
        ),
    ]
