# Generated by Django 3.0.5 on 2020-04-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='letters_uz',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=5)),
            ],
        ),
    ]
