# Generated by Django 3.0.5 on 2020-04-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Letters', '0002_auto_20200417_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterUzModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_id', models.IntegerField()),
                ('letter', models.CharField(max_length=5)),
            ],
        ),
    ]
