# Generated by Django 3.0.5 on 2020-04-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Letters', '0003_letteruzmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LetterUzModel',
        ),
    ]
